export interface Quote {
  text: string;
  author: string;
}

/**
 * Banco de frases motivacionais. A troca a cada hora não depende de nenhum
 * agendamento externo: o índice é calculado a partir da hora atual (UTC),
 * então todo mundo vê a mesma frase durante a mesma hora, e ela muda sozinha
 * quando a hora vira — sem cron, sem estado salvo em lugar nenhum.
 */
export const QUOTES: Quote[] = [
  { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
  { text: "Faça o que você ama e nunca terá que trabalhar um dia sequer na sua vida.", author: "Confúcio" },
  { text: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { text: "A inovação distingue um líder de um seguidor.", author: "Steve Jobs" },
  { text: "Não espere por oportunidades extraordinárias. Aproveite ocasiões comuns e faça-as grandiosas.", author: "Orison Swett Marden" },
  { text: "O único lugar onde o sucesso vem antes do trabalho é no dicionário.", author: "Albert Einstein" },
  { text: "Grandes coisas nunca vêm da zona de conforto.", author: "Anônimo" },
  { text: "A qualidade nunca é um acidente; é sempre o resultado de um esforço inteligente.", author: "John Ruskin" },
  { text: "Se você não constrói o seu sonho, alguém vai contratá-lo para ajudar a construir o dele.", author: "Tony Gaskins" },
  { text: "O que você faz hoje pode melhorar todos os seus amanhãs.", author: "Ralph Marston" },
  { text: "Não tenha medo de desistir do bom para buscar o ótimo.", author: "John D. Rockefeller" },
  { text: "A melhor forma de prever o futuro é criá-lo.", author: "Peter Drucker" },
  { text: "O único jeito de fazer um excelente trabalho é amar o que você faz.", author: "Steve Jobs" },
  { text: "Comece onde você está. Use o que você tem. Faça o que você pode.", author: "Arthur Ashe" },
  { text: "Motivação é o que te faz começar. Hábito é o que te mantém indo.", author: "Jim Ryun" },
  { text: "O sucesso não é definitivo, o fracasso não é fatal: o que conta é a coragem de continuar.", author: "Winston Churchill" },
  { text: "Nunca deixe que o medo de perder seja maior que a vontade de vencer.", author: "Anônimo" },
  { text: "A disciplina é a ponte entre metas e realizações.", author: "Jim Rohn" },
  { text: "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.", author: "Zig Ziglar" },
  { text: "Marketing é uma batalha de percepções, não de produtos.", author: "Al Ries" },
  { text: "O objetivo do marketing é conhecer e entender tão bem o cliente que o produto se venda sozinho.", author: "Peter Drucker" },
  { text: "As pessoas não compram o que você faz, elas compram por que você faz.", author: "Simon Sinek" },
  { text: "Conteúdo é rei, mas distribuição é rainha e governa a casa.", author: "Gary Vaynerchuk" },
  { text: "Marketing não é mais sobre as coisas que você faz, é sobre as histórias que você conta.", author: "Seth Godin" },
  { text: "Não encontre clientes para seus produtos, encontre produtos para seus clientes.", author: "Seth Godin" },
  { text: "O melhor jeito de vender algo é não vender nada. Ganhe a confiança de alguém que precisa de conselho.", author: "Rand Fishkin" },
  { text: "Publicidade é a arte de convencer as pessoas a gastar dinheiro que não têm com algo que não precisam.", author: "Will Rogers" },
  { text: "Faça publicidade ou venda seu produto por atacado.", author: "Claude Hopkins" },
  { text: "A propaganda que não vende, não é criativa.", author: "David Ogilvy" },
  { text: "O consumidor não é idiota; ele é sua esposa.", author: "David Ogilvy" },
  { text: "Se você trabalha só por dinheiro, nunca vai enriquecer. Mas se você ama o que faz e coloca o cliente em primeiro lugar, o sucesso será seu.", author: "Ray Kroc" },
  { text: "A diferença entre um sonho e uma meta é a data.", author: "Anônimo" },
  { text: "Toda conquista começa com a decisão de tentar.", author: "Gail Devers" },
  { text: "O fracasso é apenas a oportunidade de recomeçar de novo, de forma mais inteligente.", author: "Henry Ford" },
  { text: "Não importa o quão devagar você vá, desde que você não pare.", author: "Confúcio" },
  { text: "Grande parte do que chamamos de gestão consiste em dificultar o trabalho das pessoas.", author: "Peter Drucker" },
  { text: "Cultura come estratégia no café da manhã.", author: "Peter Drucker" },
  { text: "O que não é medido não é gerenciado.", author: "Peter Drucker" },
  { text: "Eficiência é fazer as coisas certo; eficácia é fazer as coisas certas.", author: "Peter Drucker" },
  { text: "A melhor maneira de ter uma boa ideia é ter muitas ideias.", author: "Linus Pauling" },
  { text: "Não tenha medo de ir devagar, tenha medo apenas de ficar parado.", author: "Provérbio chinês" },
  { text: "O tempo que você gasta se preparando é o que separa profissionais de amadores.", author: "Anônimo" },
  { text: "Todo especialista já foi um iniciante.", author: "Helen Hayes" },
  { text: "A tecnologia é melhor quando aproxima as pessoas.", author: "Matt Mullenweg" },
  { text: "Não é a espécie mais forte que sobrevive, nem a mais inteligente, mas a mais adaptável à mudança.", author: "Charles Darwin" },
  { text: "Os dados são o novo petróleo.", author: "Clive Humby" },
  { text: "Sem dados, você é só mais uma pessoa com uma opinião.", author: "W. Edwards Deming" },
  { text: "A simplicidade é o último grau de sofisticação.", author: "Leonardo da Vinci" },
  { text: "Design não é apenas como algo parece. Design é como algo funciona.", author: "Steve Jobs" },
  { text: "Feito é melhor que perfeito.", author: "Sheryl Sandberg" },
  { text: "Se você não está disposto a arriscar o incomum, terá que se conformar com o comum.", author: "Jim Rohn" },
  { text: "O maior risco é não correr nenhum risco.", author: "Mark Zuckerberg" },
  { text: "Comece antes de estar pronto.", author: "Steven Pressfield" },
  { text: "A ação é a chave fundamental para todo sucesso.", author: "Pablo Picasso" },
  { text: "Não conte os dias, faça os dias contarem.", author: "Muhammad Ali" },
  { text: "A jornada de mil quilômetros começa com um único passo.", author: "Lao Tsé" },
  { text: "Você perde 100% dos tiros que não dá.", author: "Wayne Gretzky" },
  { text: "O que quer que a mente possa conceber e acreditar, ela pode alcançar.", author: "Napoleon Hill" },
  { text: "Seja você mesmo; todos os outros já existem.", author: "Oscar Wilde" },
  { text: "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.", author: "Charles Swindoll" },
  { text: "Ninguém pode fazer você se sentir inferior sem o seu consentimento.", author: "Eleanor Roosevelt" },
  { text: "O importante não é vencer todos os dias, mas lutar sempre.", author: "Waldemar Valle Martins" },
  { text: "Transformar o impossível em possível é sempre divertido.", author: "Jim Lovell" },
  { text: "Não deixe o barulho da opinião dos outros abafar sua própria voz interior.", author: "Steve Jobs" },
  { text: "Aquilo que não nos mata nos fortalece.", author: "Friedrich Nietzsche" },
  { text: "Um objetivo bem definido já está pela metade andado.", author: "Abraham Lincoln" },
  { text: "As pessoas de sucesso encontram maneiras de fazer as coisas darem certo, ao invés de encontrar desculpas.", author: "Anônimo" },
  { text: "Você é a média das cinco pessoas com quem mais convive.", author: "Jim Rohn" },
  { text: "Trate as pessoas como se fossem o que deveriam ser e ajudá-las-á a se tornar o que são capazes de ser.", author: "Johann Wolfgang von Goethe" },
  { text: "A liderança é a capacidade de transformar visão em realidade.", author: "Warren Bennis" },
  { text: "Um bom líder leva as pessoas aonde elas querem ir. Um ótimo líder leva as pessoas aonde elas não pensavam que poderiam ir.", author: "Rosalynn Carter" },
  { text: "As pessoas esquecem o que você disse, esquecem o que você fez, mas nunca esquecem como você as fez sentir.", author: "Maya Angelou" },
  { text: "Trabalho em equipe é a capacidade de trabalhar juntos em direção a uma visão comum.", author: "Andrew Carnegie" },
  { text: "Sozinhos vamos mais rápido, juntos vamos mais longe.", author: "Provérbio africano" },
  { text: "Nenhum de nós é tão inteligente quanto todos nós juntos.", author: "Ken Blanchard" },
  { text: "A qualidade do seu foco determina a qualidade da sua vida.", author: "Robin Sharma" },
  { text: "Onde há vontade, há um caminho.", author: "Provérbio inglês" },
  { text: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta à mudança.", author: "Charles Darwin" },
  { text: "O único lugar onde seu sonho se torna impossível é na sua própria mente.", author: "Robert Kiyosaki" },
  { text: "Rico não é quem tem mais, é quem precisa de menos.", author: "Provérbio popular" },
  { text: "O dinheiro é um péssimo mestre, mas um excelente servo.", author: "P.T. Barnum" },
  { text: "Não trabalhe por dinheiro. Faça o dinheiro trabalhar para você.", author: "Robert Kiyosaki" },
  { text: "O maior perigo para a maioria de nós não é que nossa meta seja alta demais e não a alcancemos, mas que seja baixa demais e a atinjamos.", author: "Michelangelo" },
  { text: "Sonhe grande e ouse falhar.", author: "Norman Vaughan" },
  { text: "A confiança em si mesmo é o primeiro segredo do sucesso.", author: "Ralph Waldo Emerson" },
  { text: "Nada na vida deve ser temido, apenas compreendido.", author: "Marie Curie" },
  { text: "A imaginação é mais importante que o conhecimento.", author: "Albert Einstein" },
  { text: "Aprender é a única coisa que a mente nunca se cansa, nunca tem medo e nunca se arrepende.", author: "Leonardo da Vinci" },
  { text: "A mente que se abre a uma nova ideia jamais volta ao seu tamanho original.", author: "Albert Einstein" },
  { text: "Investir em conhecimento rende sempre os melhores juros.", author: "Benjamin Franklin" },
  { text: "O verdadeiro teste não é se você evita esse fracasso, porque você não vai. É se você deixa que ele te vença.", author: "Barack Obama" },
  { text: "Não julgue cada dia pela colheita que você recolhe, mas pelas sementes que você planta.", author: "Robert Louis Stevenson" },
  { text: "A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor época é agora.", author: "Provérbio chinês" },
  { text: "Faça hoje o que os outros não querem, e amanhã você viverá como os outros não podem.", author: "Anônimo" },
  { text: "O trabalho duro vence o talento quando o talento não trabalha duro.", author: "Tim Notke" },
  { text: "Você não pode usar um relógio de ontem para saber que horas são hoje.", author: "Jim Rohn" },
  { text: "A excelência não é um ato, mas um hábito.", author: "Aristóteles" },
  { text: "Somos o que repetidamente fazemos. A excelência, portanto, não é um feito, mas um hábito.", author: "Will Durant" },
  { text: "Fortuna favorece a mente preparada.", author: "Louis Pasteur" },
  { text: "Não há vento favorável para quem não sabe a que porto se dirige.", author: "Sêneca" },
  { text: "Planeje seu trabalho e trabalhe seu plano.", author: "Napoleon Hill" },
  { text: "A perfeição não é atingível, mas se perseguirmos a perfeição podemos alcançar a excelência.", author: "Vince Lombardi" },
  { text: "Todo grande negócio começou pequeno.", author: "Sam Walton" },
  { text: "Seus clientes mais insatisfeitos são sua maior fonte de aprendizado.", author: "Bill Gates" },
  { text: "É preciso 20 anos para construir uma reputação e cinco minutos para destruí-la.", author: "Warren Buffett" },
  { text: "O preço é o que você paga. O valor é o que você recebe.", author: "Warren Buffett" },
  { text: "A melhor propaganda é feita por clientes satisfeitos.", author: "Philip Kotler" },
];

/**
 * Retorna a frase "da hora" (UTC) — determinística: a mesma frase aparece
 * pra todo mundo durante a mesma hora, e muda sozinha quando a hora vira.
 */
export function getQuoteForNow(now: Date = new Date()): Quote {
  const hourBucket = Math.floor(now.getTime() / (60 * 60 * 1000));
  const index = ((hourBucket % QUOTES.length) + QUOTES.length) % QUOTES.length;
  return QUOTES[index];
}
